export const SHOWS_A = [

  {
    title: "Breaking Bad",
    year: 2008,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 5,
    overview: "A chemistry teacher turned methamphetamine manufacturer.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/501/1253519.jpg",
    externalId: "tmdb-1396",
    streamingService: "Netflix",
  },
  {
    title: "Stranger Things",
    year: 2016,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 4,
    overview: "Kids in Hawkins face supernatural forces.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/595/1489169.jpg",
    externalId: "tmdb-66732",
    streamingService: "Netflix",
  },
  {
    title: "The Office",
    year: 2005,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 9,
    overview: "A mockumentary on office life at Dunder Mifflin.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/481/1204342.jpg",
    externalId: "tmdb-2316",
    streamingService: "Peacock",
  },
  {
    title: "Game of Thrones",
    year: 2011,
    mediaType: "tv",
    genre: "Fantasy",
    totalSeasons: 8,
    overview: "Noble families fight for control of Westeros.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/498/1245274.jpg",
    externalId: "tmdb-1399",
    streamingService: "Max",
  },
  {
    title: "The Bear",
    year: 2022,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 3,
    overview: "A young chef takes over his family's sandwich shop.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/629/1574642.jpg",
    externalId: "tmdb-136315",
    streamingService: "Hulu",
  },
  {
    title: "Severance",
    year: 2022,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 2,
    overview: "Office workers surgically split work and personal memories.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/548/1371406.jpg",
    externalId: "tmdb-95396",
    streamingService: "Apple TV+",
  },
  {
    title: "Ted Lasso",
    year: 2020,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 3,
    overview: "An American football coach manages a British soccer team.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/634/1585930.jpg",
    externalId: "tmdb-97546",
    streamingService: "Apple TV+",
  },
  {
    title: "The Last of Us",
    year: 2023,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 1,
    overview: "Survivors navigate a post-apocalyptic America.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/563/1409008.jpg",
    externalId: "tmdb-100088",
    streamingService: "Max",
  },
  {
    title: "Succession",
    year: 2018,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 4,
    overview: "A media dynasty fights over who will take the throne.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/453/1134275.jpg",
    externalId: "tmdb-85552",
    streamingService: "Max",
  },
  {
    title: "Shogun",
    year: 2024,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 1,
    overview: "An English sailor becomes embroiled in feudal Japan.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/506/1265637.jpg",
    externalId: "tmdb-126308",
    streamingService: "Hulu",
  }
];
