export const SHOWS_D = [
  {
    title: "The Office",
    year: 2005,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 9,
    overview: "A mockumentary on office life at Dunder Mifflin.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/481/1204342.jpg",
    externalId: "tmdb-2316",
    streamingService: "Peacock",
  },
  {
    title: "Parks and Recreation",
    year: 2009,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 7,
    overview: "Leslie Knope navigates local government in Pawnee.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/481/1204341.jpg",
    externalId: "tmdb-8592",
    streamingService: "Peacock",
  },
  {
    title: "Poker Face",
    year: 2023,
    mediaType: "tv",
    genre: "Crime",
    totalSeasons: 2,
    overview: "A woman with a knack for spotting lies solves mysteries on the road.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/567/1419482.jpg",
    externalId: "tmdb-153312",
    streamingService: "Peacock",
  },
  {
    title: "Twisted Metal",
    year: 2023,
    mediaType: "tv",
    genre: "Action",
    totalSeasons: 1,
    overview: "A milkman drives deadly vehicles across a post-apocalyptic America.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/581/1452707.jpg",
    externalId: "tmdb-114472",
    streamingService: "Peacock",
  },
  {
    title: "Bel-Air",
    year: 2022,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 3,
    overview: "A dramatic reimagining of The Fresh Prince of Bel-Air.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/599/1499439.jpg",
    externalId: "tmdb-124998",
    streamingService: "Peacock",
  },
  {
    title: "Yellowstone",
    year: 2018,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 5,
    overview: "The Dutton family fights to protect their Montana ranch.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/545/1362616.jpg",
    externalId: "tmdb-73586",
    streamingService: "Paramount+",
  },
  {
    title: "1923",
    year: 2022,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 1,
    overview: "The Duttons face drought, prohibition, and upheaval.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/557/1392576.jpg",
    externalId: "tmdb-157741",
    streamingService: "Paramount+",
  },
  {
    title: "Tulsa King",
    year: 2022,
    mediaType: "tv",
    genre: "Crime",
    totalSeasons: 2,
    overview: "A New York mobster builds a new empire in Tulsa.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/588/1471782.jpg",
    externalId: "tmdb-156916",
    streamingService: "Paramount+",
  },
  {
    title: "Star Trek: Strange New Worlds",
    year: 2022,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 2,
    overview: "Captain Pike explores strange new worlds aboard the Enterprise.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/635/1589217.jpg",
    externalId: "tmdb-103516",
    streamingService: "Paramount+",
  },
  {
    title: "Frasier",
    year: 2023,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 1,
    overview: "Frasier Crane starts a new chapter in Boston.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/535/1339506.jpg",
    externalId: "tmdb-213713",
    streamingService: "Paramount+",
  },
  {
    title: "Inception",
    year: 2010,
    mediaType: "movie",
    genre: "Sci-Fi",
    overview: "A thief who steals secrets through dream-sharing technology.",
    posterUrl: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    externalId: "tmdb-27205",
    streamingService: "Max",
  },
  {
    title: "Interstellar",
    year: 2014,
    mediaType: "movie",
    genre: "Sci-Fi",
    overview: "Explorers travel through a wormhole in space.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    externalId: "tmdb-157336",
    streamingService: "Paramount+",
  },
  {
    title: "The Dark Knight",
    year: 2008,
    mediaType: "movie",
    genre: "Action",
    overview: "Batman faces the Joker in Gotham City.",
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    externalId: "tmdb-155",
    streamingService: "Max",
  },
  {
    title: "Dune",
    year: 2021,
    mediaType: "movie",
    genre: "Sci-Fi",
    overview: "Paul Atreides must survive on the desert planet Arrakis.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNWIyNmU5MGYtZDZmNi00ZjAwLWJlYjgtZTc0ZGIxMDE4ZGYwXkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg",
    externalId: "tmdb-438631",
    streamingService: "Max",
  },
  {
    title: "Dune: Part Two",
    year: 2024,
    mediaType: "movie",
    genre: "Sci-Fi",
    overview: "Paul unites with the Fremen to wage war against House Harkonnen.",
    posterUrl: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    externalId: "tmdb-693134",
    streamingService: "Max",
  },
  {
    title: "Barbie",
    year: 2023,
    mediaType: "movie",
    genre: "Comedy",
    overview: "Barbie leaves Barbieland for the real world.",
    posterUrl: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    externalId: "tmdb-346698",
    streamingService: "Max",
  },
  {
    title: "Oppenheimer",
    year: 2023,
    mediaType: "movie",
    genre: "Drama",
    overview: "The story of J. Robert Oppenheimer and the atomic bomb.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    externalId: "tmdb-872585",
    streamingService: "Peacock",
  },
  {
    title: "Everything Everywhere All at Once",
    year: 2022,
    mediaType: "movie",
    genre: "Comedy",
    overview: "A laundromat owner is pulled into a multiverse adventure.",
    posterUrl: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    externalId: "tmdb-545611",
    streamingService: "Prime Video",
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    year: 2023,
    mediaType: "movie",
    genre: "Animation",
    overview: "Miles Morales journeys across the multiverse.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    externalId: "tmdb-569094",
    streamingService: "Netflix",
  },
];
