export const SHOWS_A = [
  {
    title: "Breaking Bad",
    year: 2008,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 5,
    overview: "A chemistry teacher turned methamphetamine manufacturer.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/501/1253519.jpg",
    externalId: "tmdb-1396",
    streamingService: "Netflix",
  },
  {
    title: "Stranger Things",
    year: 2016,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 4,
    overview: "Kids in Hawkins face supernatural forces.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/595/1489169.jpg",
    externalId: "tmdb-66732",
    streamingService: "Netflix",
  },
  {
    title: "Squid Game",
    year: 2021,
    mediaType: "tv",
    genre: "Thriller",
    totalSeasons: 2,
    overview: "Contestants risk everything in deadly children's games for a huge cash prize.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/576/1440521.jpg",
    externalId: "tmdb-93405",
    streamingService: "Netflix",
  },
  {
    title: "Arcane",
    year: 2021,
    mediaType: "tv",
    genre: "Animation",
    totalSeasons: 2,
    overview: "Twin cities of Piltover and Zaun collide.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/536/1340287.jpg",
    externalId: "tmdb-94605",
    streamingService: "Netflix",
  },
  {
    title: "The Witcher",
    year: 2019,
    mediaType: "tv",
    genre: "Fantasy",
    totalSeasons: 3,
    overview: "Geralt of Rivia hunts monsters in a politically fractured world.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/594/1486674.jpg",
    externalId: "tmdb-71912",
    streamingService: "Netflix",
  },
  {
    title: "Wednesday",
    year: 2022,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 1,
    overview: "Wednesday Addams investigates mysteries at Nevermore Academy.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/586/1466410.jpg",
    externalId: "tmdb-119051",
    streamingService: "Netflix",
  },
  {
    title: "Dark",
    year: 2017,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 3,
    overview: "A missing child unravels a time-travel conspiracy in a German town.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/504/1262352.jpg",
    externalId: "tmdb-70523",
    streamingService: "Netflix",
  },
  {
    title: "The Crown",
    year: 2016,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 6,
    overview: "The reign of Queen Elizabeth II across decades.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/632/1580063.jpg",
    externalId: "tmdb-70522",
    streamingService: "Netflix",
  },
  {
    title: "Ozark",
    year: 2017,
    mediaType: "tv",
    genre: "Crime",
    totalSeasons: 4,
    overview: "A financial planner relocates his family to the Ozarks to launder money.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/398/996611.jpg",
    externalId: "tmdb-69740",
    streamingService: "Netflix",
  },
  {
    title: "Bridgerton",
    year: 2020,
    mediaType: "tv",
    genre: "Romance",
    totalSeasons: 3,
    overview: "Regency-era high society romance and scandal.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/614/1535959.jpg",
    externalId: "tmdb-94880",
    streamingService: "Netflix",
  },
  {
    title: "Money Heist",
    year: 2017,
    mediaType: "tv",
    genre: "Crime",
    totalSeasons: 5,
    overview: "A criminal mastermind plans the biggest heist in Spanish history.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/430/1076004.jpg",
    externalId: "tmdb-71446",
    streamingService: "Netflix",
  },
  {
    title: "Black Mirror",
    year: 2011,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 6,
    overview: "Anthology exploring the dark side of technology.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/564/1411764.jpg",
    externalId: "tmdb-42009",
    streamingService: "Netflix",
  },
  {
    title: "The Umbrella Academy",
    year: 2019,
    mediaType: "tv",
    genre: "Action",
    totalSeasons: 4,
    overview: "Dysfunctional siblings with powers reunite to save the world.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/529/1324589.jpg",
    externalId: "tmdb-75006",
    streamingService: "Netflix",
  },
  {
    title: "Narcos",
    year: 2015,
    mediaType: "tv",
    genre: "Crime",
    totalSeasons: 3,
    overview: "The rise of the cocaine trade in Colombia.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/498/1246087.jpg",
    externalId: "tmdb-63351",
    streamingService: "Netflix",
  },
  {
    title: "Emily in Paris",
    year: 2020,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 4,
    overview: "An American marketing executive navigates life in Paris.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/604/1510920.jpg",
    externalId: "tmdb-100757",
    streamingService: "Netflix",
  },
  {
    title: "Game of Thrones",
    year: 2011,
    mediaType: "tv",
    genre: "Fantasy",
    totalSeasons: 8,
    overview: "Noble families fight for control of Westeros.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/498/1245274.jpg",
    externalId: "tmdb-1399",
    streamingService: "Max",
  },
  {
    title: "The Last of Us",
    year: 2023,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 1,
    overview: "Survivors navigate a post-apocalyptic America.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/563/1409008.jpg",
    externalId: "tmdb-100088",
    streamingService: "Max",
  },
  {
    title: "Succession",
    year: 2018,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 4,
    overview: "A media dynasty fights over who will take the throne.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/453/1134275.jpg",
    externalId: "tmdb-85552",
    streamingService: "Max",
  },
  {
    title: "House of the Dragon",
    year: 2022,
    mediaType: "tv",
    genre: "Fantasy",
    totalSeasons: 2,
    overview: "The Targaryen civil war that precedes Game of Thrones.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/627/1568449.jpg",
    externalId: "tmdb-94997",
    streamingService: "Max",
  },
];
