export const SHOWS_E = [
  {
    title: "Top Gun: Maverick",
    year: 2022,
    mediaType: "movie",
    genre: "Action",
    overview: "Maverick trains a new generation of Top Gun pilots.",
    posterUrl: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    externalId: "tmdb-361743",
    streamingService: "Paramount+",
  },
  {
    title: "The Batman",
    year: 2022,
    mediaType: "movie",
    genre: "Action",
    overview: "Batman investigates corruption in Gotham City.",
    posterUrl: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    externalId: "tmdb-414906",
    streamingService: "Max",
  },
  {
    title: "Guardians of the Galaxy Vol. 3",
    year: 2023,
    mediaType: "movie",
    genre: "Action",
    overview: "The Guardians face their past to save one of their own.",
    posterUrl: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    externalId: "tmdb-447365",
    streamingService: "Disney+",
  },
  {
    title: "Avatar: The Way of Water",
    year: 2022,
    mediaType: "movie",
    genre: "Sci-Fi",
    overview: "The Sully family explores the oceans of Pandora.",
    posterUrl: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    externalId: "tmdb-76600",
    streamingService: "Disney+",
  },
  {
    title: "Black Panther: Wakanda Forever",
    year: 2022,
    mediaType: "movie",
    genre: "Action",
    overview: "Wakanda fights to protect its future after T'Challa's death.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYWY5NDY1ZjItZDQxMy00MTAzLTgyOGQtNTQxYjFiMzZjMjUyXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    externalId: "tmdb-505642",
    streamingService: "Disney+",
  },
  {
    title: "Glass Onion",
    year: 2022,
    mediaType: "movie",
    genre: "Mystery",
    overview: "Benoit Blanc investigates a murder among the ultra-wealthy.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMzI2ZDYxZTEtMzVlOC00OTUyLTgyNTAtYWFhNmRhZjAzZWE1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    externalId: "tmdb-661374",
    streamingService: "Netflix",
  },
  {
    title: "The Menu",
    year: 2022,
    mediaType: "movie",
    genre: "Thriller",
    overview: "A couple visits an exclusive restaurant with a shocking twist.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BN2Q0YWE1MjktODJlMi00NTRiLWI2ZTctZTAxNjkyODVjM2EyXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
    externalId: "tmdb-830784",
    streamingService: "Hulu",
  },
  {
    title: "Nope",
    year: 2022,
    mediaType: "movie",
    genre: "Horror",
    overview: "Siblings witness an otherworldly spectacle in the California desert.",
    posterUrl: "https://image.tmdb.org/t/p/w500/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
    externalId: "tmdb-762504",
    streamingService: "Peacock",
  },
  {
    title: "Killers of the Flower Moon",
    year: 2023,
    mediaType: "movie",
    genre: "Drama",
    overview: "Osage murders and the birth of the FBI.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZWY5ZDVjNTUtODI5Yy00MjFhLWEyM2EtYzZjM2VjZTI0MTBjXkEyXkFqcGc@._V1_SX300.jpg",
    externalId: "tmdb-466420",
    streamingService: "Apple TV+",
  },
  {
    title: "Napoleon",
    year: 2023,
    mediaType: "movie",
    genre: "Drama",
    overview: "The rise and fall of Napoleon Bonaparte.",
    posterUrl: "https://image.tmdb.org/t/p/w500/jE5o7y9K6pZtWNNMEw3IdpHuncR.jpg",
    externalId: "tmdb-753342",
    streamingService: "Apple TV+",
  },
  {
    title: "The Super Mario Bros. Movie",
    year: 2023,
    mediaType: "movie",
    genre: "Animation",
    overview: "Mario and Luigi journey into the Mushroom Kingdom.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOWFmNmY2YjAtZTgyNy00MjBmLWI1YWMtMjFjZjkxYjYyOTVmXkEyXkFqcGc@._V1_QL75_UX380_CR0,20,380,562_.jpg",
    externalId: "tmdb-502356",
    streamingService: "Peacock",
  },
  {
    title: "John Wick: Chapter 4",
    year: 2023,
    mediaType: "movie",
    genre: "Action",
    overview: "John Wick takes on the High Table around the world.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BY2Q2ZmI5ZjUtNWVhMC00YzJkLTlmYjMtY2RmZDhkNzEzYjZhXkEyXkFqcGc@._V1_SX300.jpg",
    externalId: "tmdb-603692",
    streamingService: "Prime Video",
  },
  {
    title: "Air",
    year: 2023,
    mediaType: "movie",
    genre: "Drama",
    overview: "Nike's pursuit of a partnership with Michael Jordan.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNjdjYzJkZmUtZDNiMC00MzQ0LWE2MGEtYTk4ZGM4NzFkMzM3XkEyXkFqcGc@._V1_SX300.jpg",
    externalId: "tmdb-966220",
    streamingService: "Prime Video",
  },
  {
    title: "Cocaine Bear",
    year: 2023,
    mediaType: "movie",
    genre: "Comedy",
    overview: "A bear goes on a rampage after ingesting cocaine.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjg3MmNiNWQtOWI1OS00MjE2LWFhYzYtMWY0NWRhZmVkMGFiXkEyXkFqcGc@._V1_QL75_UY562_CR0,0,380,562_.jpg",
    externalId: "tmdb-739405",
    streamingService: "Peacock",
  },
  {
    title: "Elemental",
    year: 2023,
    mediaType: "movie",
    genre: "Animation",
    overview: "Fire and water residents form an unlikely bond in Element City.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNjU2MjE1OGItZjdmYS00ZmIyLTljNjYtOWI5ZGRkZjM4NDEwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    externalId: "tmdb-976573",
    streamingService: "Disney+",
  },
  {
    title: "Mission: Impossible – Dead Reckoning Part One",
    year: 2023,
    mediaType: "movie",
    genre: "Action",
    overview: "Ethan Hunt races to control a dangerous AI.",
    posterUrl: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
    externalId: "tmdb-575264",
    streamingService: "Paramount+",
  },
  {
    title: "The Hunger Games: The Ballad of Songbirds & Snakes",
    year: 2023,
    mediaType: "movie",
    genre: "Action",
    overview: "Young Coriolanus Snow mentors a Hunger Games tribute.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZDk2YjNhYzEtYzg2ZC00OWEwLWJhYzgtMGUzMWVjNDFmYzI5XkEyXkFqcGc@._V1_SX300.jpg",
    externalId: "tmdb-695721",
    streamingService: "Hulu",
  },
  {
    title: "Poor Things",
    year: 2023,
    mediaType: "movie",
    genre: "Comedy",
    overview: "A young woman brought back to life embarks on a fantastical journey.",
    posterUrl: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    externalId: "tmdb-792307",
    streamingService: "Hulu",
  },
  {
    title: "Past Lives",
    year: 2023,
    mediaType: "movie",
    genre: "Drama",
    overview: "Two childhood friends reunite decades later in New York.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYjQyMTNhNjUtN2VmYy00NWRhLTkwOTctMGVmNTBmNDIxYjZhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    externalId: "tmdb-666277",
    streamingService: "Paramount+",
  },
];
