export const SHOWS_B = [
  {
    title: "Squid Game",
    year: 2021,
    mediaType: "tv",
    genre: "Thriller",
    totalSeasons: 2,
    overview: "Contestants risk everything in deadly children's games for a huge cash prize.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/612/1531540.jpg",
    externalId: "tmdb-93405",
    streamingService: "Netflix",
  },
  {
    title: "Inception",
    year: 2010,
    mediaType: "movie",
    genre: "Sci-Fi",
    overview: "A thief who steals secrets through dream-sharing technology.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    externalId: "tmdb-27205",
    streamingService: "Theatrical",
  },
  {
    title: "Interstellar",
    year: 2014,
    mediaType: "movie",
    genre: "Sci-Fi",
    overview: "Explorers travel through a wormhole in space.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    externalId: "tmdb-157336",
    streamingService: "Paramount+",
  },
  {
    title: "The Dark Knight",
    year: 2008,
    mediaType: "movie",
    genre: "Action",
    overview: "Batman faces the Joker in Gotham City.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    externalId: "tmdb-155",
    streamingService: "Max",
  },
  {
    title: "Dune",
    year: 2021,
    mediaType: "movie",
    genre: "Sci-Fi",
    overview: "Paul Atreides must survive on the desert planet Arrakis.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNWIyNmU5MGYtZDZmNi00ZjAwLWJlYjgtZTc0ZGIxMDE4ZGYwXkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg",
    externalId: "tmdb-438631",
    streamingService: "Max",
  },
  {
    title: "Arcane",
    year: 2021,
    mediaType: "tv",
    genre: "Animation",
    totalSeasons: 2,
    overview: "Twin cities of Piltover and Zaun collide.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/536/1340287.jpg",
    externalId: "tmdb-94605",
    streamingService: "Netflix",
  },
  {
    title: "Abbott Elementary",
    year: 2021,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 3,
    overview: "Teachers at an underfunded Philadelphia school.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/586/1467109.jpg",
    externalId: "tmdb-124418",
    streamingService: "Hulu",
  },
  {
    title: "The Mandalorian",
    year: 2019,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 3,
    overview: "A lone bounty hunter in the outer reaches of the galaxy.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/501/1253498.jpg",
    externalId: "tmdb-82856",
    streamingService: "Disney+",
  },
  {
    title: "Only Murders in the Building",
    year: 2021,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 4,
    overview: "Three strangers investigate a murder in their apartment building.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/586/1466415.jpg",
    externalId: "tmdb-107113",
    streamingService: "Hulu",
  },
  {
    title: "The Boys",
    year: 2019,
    mediaType: "tv",
    genre: "Action",
    totalSeasons: 4,
    overview: "Vigilantes take on corrupt superheroes.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/501/1253511.jpg",
    externalId: "tmdb-76479",
    streamingService: "Prime Video",
  },
];
