export const SHOWS_C = [
  {
    title: "Reservation Dogs",
    year: 2021,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 3,
    overview: "Indigenous teens navigate life in rural Oklahoma.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/475/1189118.jpg",
    externalId: "tmdb-125910",
    streamingService: "Hulu",
  },
  {
    title: "Solar Opposites",
    year: 2020,
    mediaType: "tv",
    genre: "Animation",
    totalSeasons: 5,
    overview: "Alien family tries to blend in on Earth.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/592/1480191.jpg",
    externalId: "tmdb-92588",
    streamingService: "Hulu",
  },
  {
    title: "The Great",
    year: 2020,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 3,
    overview: "Satirical take on Catherine the Great's rise to power.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/460/1151199.jpg",
    externalId: "tmdb-92051",
    streamingService: "Hulu",
  },
  {
    title: "The Boys",
    year: 2019,
    mediaType: "tv",
    genre: "Action",
    totalSeasons: 4,
    overview: "Vigilantes take on corrupt superheroes.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/619/1547768.jpg",
    externalId: "tmdb-76479",
    streamingService: "Prime Video",
  },
  {
    title: "The Marvelous Mrs. Maisel",
    year: 2017,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 5,
    overview: "A 1950s housewife becomes a stand-up comedian.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/456/1141825.jpg",
    externalId: "tmdb-70796",
    streamingService: "Prime Video",
  },
  {
    title: "The Expanse",
    year: 2015,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 6,
    overview: "A conspiracy threatens peace across the solar system.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/445/1114081.jpg",
    externalId: "tmdb-63639",
    streamingService: "Prime Video",
  },
  {
    title: "Reacher",
    year: 2022,
    mediaType: "tv",
    genre: "Action",
    totalSeasons: 3,
    overview: "Jack Reacher investigates crimes across America.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/636/1591350.jpg",
    externalId: "tmdb-108978",
    streamingService: "Prime Video",
  },
  {
    title: "Fallout",
    year: 2024,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 1,
    overview: "Survivors emerge from vaults into a nuclear wasteland.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/599/1499142.jpg",
    externalId: "tmdb-106379",
    streamingService: "Prime Video",
  },
  {
    title: "Invincible",
    year: 2021,
    mediaType: "tv",
    genre: "Animation",
    totalSeasons: 2,
    overview: "A teen inherits his father's superpowers—and secrets.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/618/1545777.jpg",
    externalId: "tmdb-95557",
    streamingService: "Prime Video",
  },
  {
    title: "Upload",
    year: 2020,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 3,
    overview: "A man is uploaded to a digital afterlife after dying.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/586/1466414.jpg",
    externalId: "tmdb-94756",
    streamingService: "Prime Video",
  },
  {
    title: "The Wheel of Time",
    year: 2021,
    mediaType: "tv",
    genre: "Fantasy",
    totalSeasons: 3,
    overview: "Young villagers discover they may be key to saving the world.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/564/1411765.jpg",
    externalId: "tmdb-94722",
    streamingService: "Prime Video",
  },
  {
    title: "Severance",
    year: 2022,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 2,
    overview: "Office workers surgically split work and personal memories.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/548/1371406.jpg",
    externalId: "tmdb-95396",
    streamingService: "Apple TV+",
  },
  {
    title: "Ted Lasso",
    year: 2020,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 3,
    overview: "An American football coach manages a British soccer team.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/634/1585930.jpg",
    externalId: "tmdb-97546",
    streamingService: "Apple TV+",
  },
  {
    title: "The Morning Show",
    year: 2019,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 3,
    overview: "Anchors navigate scandal and power at a morning news show.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/594/1485135.jpg",
    externalId: "tmdb-90228",
    streamingService: "Apple TV+",
  },
  {
    title: "Foundation",
    year: 2021,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 2,
    overview: "A mathematician predicts the fall of a galactic empire.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/573/1433544.jpg",
    externalId: "tmdb-93740",
    streamingService: "Apple TV+",
  },
  {
    title: "Slow Horses",
    year: 2022,
    mediaType: "tv",
    genre: "Thriller",
    totalSeasons: 4,
    overview: "Misfit MI5 agents take on cases nobody else wants.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/637/1593462.jpg",
    externalId: "tmdb-124364",
    streamingService: "Apple TV+",
  },
  {
    title: "Silo",
    year: 2023,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 2,
    overview: "Residents of a giant underground silo question their world.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/631/1577677.jpg",
    externalId: "tmdb-125988",
    streamingService: "Apple TV+",
  },
  {
    title: "For All Mankind",
    year: 2019,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 4,
    overview: "Alternate history of the space race after the Soviets land first.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/616/1541416.jpg",
    externalId: "tmdb-87917",
    streamingService: "Apple TV+",
  },
  {
    title: "Shrinking",
    year: 2023,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 2,
    overview: "A grieving therapist starts saying exactly what he thinks.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/610/1527402.jpg",
    externalId: "tmdb-136311",
    streamingService: "Apple TV+",
  },
];
