export const SHOWS_F = [
  {
    title: "Anatomy of a Fall",
    year: 2023,
    mediaType: "movie",
    genre: "Thriller",
    overview: "A writer is suspected after her husband's death.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYTk3MjFkZmQtMThiYi00N2JhLTk2YzItZTE5ZGUxZTIyZDVkXkEyXkFqcGc@._V1_QL75_UY562_CR2,0,380,562_.jpg",
    externalId: "tmdb-915935",
    streamingService: "Hulu",
  },
  {
    title: "Godzilla Minus One",
    year: 2023,
    mediaType: "movie",
    genre: "Action",
    overview: "Postwar Japan faces a terrifying new Godzilla.",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjc5MjllMGUtMDIwMS00ZDVkLWEzODQtM2NlMTMwMTZhNThmXkEyXkFqcGc@._V1_SX300.jpg",
    externalId: "tmdb-940551",
    streamingService: "Netflix",
  },
  {
    title: "The Night Agent",
    year: 2023,
    mediaType: "tv",
    genre: "Thriller",
    totalSeasons: 2,
    overview: "An FBI agent answers a mysterious late-night phone call.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/614/1536331.jpg",
    externalId: "tmdb-138501",
    streamingService: "Netflix",
  },
  {
    title: "Ginny & Georgia",
    year: 2021,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 2,
    overview: "A mother and daughter start over in a New England town.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/570/1427139.jpg",
    externalId: "tmdb-117164",
    streamingService: "Netflix",
  },
  {
    title: "Love Is Blind",
    year: 2020,
    mediaType: "tv",
    genre: "Reality",
    totalSeasons: 6,
    overview: "Singles propose before meeting face to face.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/613/1533160.jpg",
    externalId: "tmdb-100349",
    streamingService: "Netflix",
  },
  {
    title: "Industry",
    year: 2020,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 3,
    overview: "Young graduates compete for jobs at a London investment bank.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/608/1521293.jpg",
    externalId: "tmdb-107063",
    streamingService: "Max",
  },
  {
    title: "Perry Mason",
    year: 2020,
    mediaType: "tv",
    genre: "Crime",
    totalSeasons: 2,
    overview: "An origin story of the legendary defense attorney.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/450/1126198.jpg",
    externalId: "tmdb-90281",
    streamingService: "Max",
  },
  {
    title: "Obi-Wan Kenobi",
    year: 2022,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 1,
    overview: "Obi-Wan emerges from exile to protect young Leia.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/498/1246074.jpg",
    externalId: "tmdb-92830",
    streamingService: "Disney+",
  },
  {
    title: "The Book of Boba Fett",
    year: 2021,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 1,
    overview: "Boba Fett claims Jabba's throne on Tatooine.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/501/1253027.jpg",
    externalId: "tmdb-115036",
    streamingService: "Disney+",
  },
  {
    title: "Ramy",
    year: 2019,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 3,
    overview: "A first-generation American Muslim navigates faith and modernity.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/445/1113772.jpg",
    externalId: "tmdb-83095",
    streamingService: "Hulu",
  },
  {
    title: "Dopesick",
    year: 2021,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 1,
    overview: "The opioid epidemic through patients, prosecutors, and pharma.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/592/1480209.jpg",
    externalId: "tmdb-106611",
    streamingService: "Hulu",
  },
  {
    title: "Jack Ryan",
    year: 2018,
    mediaType: "tv",
    genre: "Action",
    totalSeasons: 4,
    overview: "CIA analyst Jack Ryan is pulled into deadly field operations.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/486/1215704.jpg",
    externalId: "tmdb-73375",
    streamingService: "Prime Video",
  },
  {
    title: "The Peripheral",
    year: 2022,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 1,
    overview: "A woman discovers a dark connection to an alternate future.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/445/1112626.jpg",
    externalId: "tmdb-95384",
    streamingService: "Prime Video",
  },
  {
    title: "Mythic Quest",
    year: 2020,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 4,
    overview: "The chaotic team behind a popular video game.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/564/1412475.jpg",
    externalId: "tmdb-94954",
    streamingService: "Apple TV+",
  },
  {
    title: "Pachinko",
    year: 2022,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 2,
    overview: "A Korean family's multi-generational saga across Japan and America.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/532/1330795.jpg",
    externalId: "tmdb-112908",
    streamingService: "Apple TV+",
  },
  {
    title: "Based on a True Story",
    year: 2023,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 1,
    overview: "A couple teams up with a serial killer for a true-crime podcast.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/542/1356251.jpg",
    externalId: "tmdb-214477",
    streamingService: "Peacock",
  },
  {
    title: "Special Ops: Lioness",
    year: 2023,
    mediaType: "tv",
    genre: "Action",
    totalSeasons: 2,
    overview: "A CIA program recruits women to infiltrate terrorist organizations.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/635/1587727.jpg",
    externalId: "tmdb-157743",
    streamingService: "Paramount+",
  },
];
