export const SHOWS_B = [
  {
    title: "The White Lotus",
    year: 2021,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 3,
    overview: "Guests and staff collide at luxury resorts.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/557/1393876.jpg",
    externalId: "tmdb-111803",
    streamingService: "Max",
  },
  {
    title: "Euphoria",
    year: 2019,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 2,
    overview: "High school students navigate love, identity, and addiction.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/621/1552657.jpg",
    externalId: "tmdb-85533",
    streamingService: "Max",
  },
  {
    title: "True Detective",
    year: 2014,
    mediaType: "tv",
    genre: "Crime",
    totalSeasons: 4,
    overview: "Anthology crime drama with haunted detectives.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/490/1226764.jpg",
    externalId: "tmdb-46648",
    streamingService: "Max",
  },
  {
    title: "Barry",
    year: 2018,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 4,
    overview: "A hitman finds unexpected purpose in acting class.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/455/1138151.jpg",
    externalId: "tmdb-70619",
    streamingService: "Max",
  },
  {
    title: "The Penguin",
    year: 2024,
    mediaType: "tv",
    genre: "Crime",
    totalSeasons: 1,
    overview: "Oswald Cobblepot rises through Gotham's underworld.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/536/1340329.jpg",
    externalId: "tmdb-206559",
    streamingService: "Max",
  },
  {
    title: "Veep",
    year: 2012,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 7,
    overview: "Political satire following a vice president's chaotic career.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/189/472887.jpg",
    externalId: "tmdb-40146",
    streamingService: "Max",
  },
  {
    title: "The Mandalorian",
    year: 2019,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 3,
    overview: "A lone bounty hunter in the outer reaches of the galaxy.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/501/1253498.jpg",
    externalId: "tmdb-82856",
    streamingService: "Disney+",
  },
  {
    title: "Loki",
    year: 2021,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 2,
    overview: "The God of Mischief navigates the TVA and the multiverse.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/478/1195717.jpg",
    externalId: "tmdb-84958",
    streamingService: "Disney+",
  },
  {
    title: "Andor",
    year: 2022,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 2,
    overview: "Cassian Andor's path to rebellion against the Empire.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/564/1411766.jpg",
    externalId: "tmdb-83867",
    streamingService: "Disney+",
  },
  {
    title: "WandaVision",
    year: 2021,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 1,
    overview: "Wanda and Vision live in a sitcom reality that hides darker truths.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/295/738028.jpg",
    externalId: "tmdb-85271",
    streamingService: "Disney+",
  },
  {
    title: "The Acolyte",
    year: 2024,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 1,
    overview: "A mystery thriller set in the High Republic era of Star Wars.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/586/1465997.jpg",
    externalId: "tmdb-114461",
    streamingService: "Disney+",
  },
  {
    title: "Percy Jackson and the Olympians",
    year: 2023,
    mediaType: "tv",
    genre: "Fantasy",
    totalSeasons: 1,
    overview: "A demigod discovers his destiny among Greek myths.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/633/1584337.jpg",
    externalId: "tmdb-117160",
    streamingService: "Disney+",
  },
  {
    title: "What If...?",
    year: 2021,
    mediaType: "tv",
    genre: "Animation",
    totalSeasons: 2,
    overview: "Animated anthology exploring alternate MCU timelines.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/543/1358372.jpg",
    externalId: "tmdb-91363",
    streamingService: "Disney+",
  },
  {
    title: "Ahsoka",
    year: 2023,
    mediaType: "tv",
    genre: "Sci-Fi",
    totalSeasons: 1,
    overview: "Ahsoka Tano investigates an emerging threat to the galaxy.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/636/1592346.jpg",
    externalId: "tmdb-202736",
    streamingService: "Disney+",
  },
  {
    title: "The Bear",
    year: 2022,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 3,
    overview: "A young chef takes over his family's sandwich shop.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/629/1574642.jpg",
    externalId: "tmdb-136315",
    streamingService: "Hulu",
  },
  {
    title: "Shogun",
    year: 2024,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 1,
    overview: "An English sailor becomes embroiled in feudal Japan.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/506/1265637.jpg",
    externalId: "tmdb-126308",
    streamingService: "Hulu",
  },
  {
    title: "Abbott Elementary",
    year: 2021,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 3,
    overview: "Teachers at an underfunded Philadelphia school.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/586/1467109.jpg",
    externalId: "tmdb-124418",
    streamingService: "Hulu",
  },
  {
    title: "Only Murders in the Building",
    year: 2021,
    mediaType: "tv",
    genre: "Comedy",
    totalSeasons: 4,
    overview: "Three strangers investigate a murder in their apartment building.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/586/1466415.jpg",
    externalId: "tmdb-107113",
    streamingService: "Hulu",
  },
  {
    title: "The Handmaid's Tale",
    year: 2017,
    mediaType: "tv",
    genre: "Drama",
    totalSeasons: 5,
    overview: "A woman fights to survive in a totalitarian theocracy.",
    posterUrl: "https://static.tvmaze.com/uploads/images/original_untouched/562/1406667.jpg",
    externalId: "tmdb-69478",
    streamingService: "Hulu",
  },
];
